sudo: required
services:
    -   docker

before_install:
    -   docker build -t farhanadis/react-test -f ./client/Dockerfile.dev ./client

script:
    -   docker run farhanadis/react-test npm test -- --coverage

after_success:
    -   docker build -t farhanadis/multi-client ./client
    -   docker build -t farhanadis/multi-nginx ./nginx
    -   docker build -t farhanadis/multi-server ./server
    -   docker build -t farhanadis/multi-worker ./worker

    -   echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    -   docker push farhanadis/multi-client
    -   docker push farhanadis/multi-nginx
    -   docker push farhanadis/multi-server
    -   docker push farhanadis/multi-worker


deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-2-679136563185
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY